services:
  mongo:
    image: mongo:4.4.29
    container_name: mongo
    build:
      context: ./configs/services/mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./configs/services/mongo/mongod.conf:/etc/mongod.conf:cached
      - mongo-data:/data/db

  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - 6379:6379

  ema:
    container_name: ema
    build:
      dockerfile: ./Exentriq-Docker/configs/projects/ema/Dev.Dockerfile
      context: ../
      no_cache: true
    ports:
      - 3002:3002
    volumes:
      - ../Exentriq-EMA:/var/app/Exentriq-EMA
      - ../Exentriq-MSP:/var/app/Exentriq-MSP:cached
    depends_on:
      - redis
      - mongo

volumes:
  mongo-data:
