services:
  mongo:
    image: mongo:4.4.29
    container_name: mongo
    build:
      context: ./configs/services/mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./configs/services/mongo/mongod.conf:/etc/mongod.conf:cached
      - mongo-data:/data/db

  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - 6379:6379

  ema:
    container_name: ema
    build:
      dockerfile: ./Exentriq-Docker/configs/projects/ema/Dev.Dockerfile
      context: ../
      no_cache: true
    ports:
      - 3002:3002
    depends_on:
      - redis
      - mongo
    volumes:
      - ../Exentriq-EMA/node_modules:/var/app/Exentriq-EMA/node_modules
      - mutagen:/var/app/Exentriq-EMA/.meteor/local
      - ../Exentriq-MSP/packages:/var/app/Exentriq-MSP/packages
#    develop:
#      watch:
#        - action: sync
#          path: ../Exentriq-MSP/packages
#          target: /var/app/Exentriq-MSP/packages
#          ignore:
#            - ../Exentriq-MSP/packages/**/*.npm
#        - action: sync
#          path: ../Exentriq-EMA/packages
#          target: /var/app/Exentriq-EMA/packages
#          ignore:
#            - ../Exentriq-EMA/packages/**/*.npm

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
      mode: "two-way-resolved"

    mutagen:
      alpha: "./../Exentriq-EMA/.meteor/local"
      beta: "volume://mutagen"

volumes:
  mutagen:
  mongo-data:
  ema-node-modules:
  ema-meteor-local:
  msp-packages-npm:

  custom-board-node-modules:
  custom-board-build:
